### ISSUE TITLE
nxdl2nyaml: xref with "" strings

### ISSUE THREAD

**Issue by lukaspie** [FAIRmat-NFDI/nyaml#13]
```xml
<group name="energy_resolution" type="NXresolution" recommended="true">
    <doc>
         Overall energy resolution of the MPES instrument
         
         This concept is related to term `10.7 ff.`_ of the ISO 18115-1:2023 standard.
         
         .. _10.7 ff.: https://www.iso.org/obp/ui/en/#iso:std:iso:18115:-1:ed-3:v1:en:term:10.7
    </doc>
```
is translated to:
```yaml
energy_resolution(NXresolution):
  exists: recommended
  doc:
   - |
    Overall energy resolution of the MPES instrument
   - |
    "xref:
      spec: ISO 18115-1:2023
      term: 10.7 ff.
      url: https://www.iso.org/obp/ui/en/#iso:std:iso:18115:-1:ed-3:v1:en:term:10.7"
```
The "" in xref are not strictly necessary. Additionally, there is a space inserted before each - |. We could also get rid of it. I propose to simplify to:
```yaml
energy_resolution(NXresolution):
  exists: recommended
  doc:
  - |
    Overall energy resolution of the MPES instrument
  - |
    xref:
      spec: ISO 18115-1:2023
      term: 10.7 ff.
      url: https://www.iso.org/obp/ui/en/#iso:std:iso:18115:-1:ed-3:v1:en:term:10.7
```
