### ISSUE TITLE
Error in backward and forward conversion

### ISSUE THREAD

**Issue by RubelMozumder** [FAIRmat-NFDI/nyaml#37]
```yaml
intensity(NX_FLOAT):
  doc: |
    Number of scattered electrons per unit time.
  dimensions:
    rank: 1
    dim: (nDet,)
```
converts to

```xml
<field name="intensity" type="NX_FLOAT">
    <doc>
         Number of scattered electrons per unit time.
    </doc>
    <dimensions rank="1">
        <dim index="1" value="nDet"/>
        <dim index="2" value=""/>
    </dimensions>
</field>
```
Having an additional `dim` element is unexpected.
