### ISSUE TITLE
Implement open enumerations

### ISSUE THREAD

**Issue by lukaspie** [FAIRmat-NFDI/nyaml#56]
https://github.com/nexusformat/definitions/pull/1521 introduced **open enumerations**, i.e., to allow values not explicitly given in the enumeration list. For this, a new attribute `open` was introduced for the enumerationTYPE, which defaults to "False". If open enumeration is used, this XML attribute should be "True".

In order to support this new feature, I suggest the following notation:
 ```xml
	<field name="mode">
		<doc>source operating mode</doc>
		<enumeration open="true">
			<item value="Single Bunch"><doc>for storage rings</doc></item>
			<item value="Multi Bunch"><doc>for storage rings</doc></item>
		</enumeration>
	</field>
```
shall be expressed in nyaml as
```yaml
  mode:
    doc: |
      source operating mode
    enumeration:
      \@open: True
      Single Bunch:
        doc: |
          for storage rings
      Multi Bunch:
        doc: |
          for storage rings
````
If `\@open` is not set, we default to <enumeration"> (i.e. open="False").

Using the `\@` notation, we avoid situations where `open` is a valid enumeration value.

Opinions @sanbrock @mkuehbach @RubelMozumder ?

**Comment by lukaspie** [comment]
Our current notation like this 
```yaml
type:
    doc: |
      type of radiation source (pick one from the enumerated list and spell exactly)
    enumeration: [Spallation Neutron Source, Pulsed Reactor Neutron Source, Reactor Neutron Source, ...]
```
will likely not be able to handle this.

Another option we could go for is to add another special keyword, like
```yaml
type:
    doc: |
      type of radiation source (pick one from the enumerated list and spell exactly)
    enumeration: [Spallation Neutron Source, Pulsed Reactor Neutron Source, Reactor Neutron Source, ...]
    open_enumeration: True
```
