### ISSUE TITLE
ISO reference in enumeration docstring breaks building of nexus definitions

### ISSUE THREAD

**Issue by domna** [FAIRmat-NFDI/nyaml#6]
This part of [NXmpes](https://github.com/FAIRmat-NFDI/nexus_definitions/blob/d5587be843a6c615ef4af179a29f24424ad75b95/contributed_definitions/nyaml/NXmpes.yaml#L536) breaks the building into html of the nexus definitions:

```yaml
...
       \@type:
          type: NX_CHAR
          exists: recommended
          doc: |
            The energy can be either stored as kinetic or as binding energy.
          enumeration: 
            kinetic: 
              doc:
              - |
                Calibrated kinetic energy axis.
              - |
                xref:
                  spec: ISO 18115-1:2023
                  term: 3.35
                  url: https://www.iso.org/obp/ui/en/#iso:std:iso:18115:-1:ed-3:v1:en:term:3.35
...
```

It can be fixed by changing the [_get_doc_line](https://github.com/FAIRmat-NFDI/nexus_definitions/blob/d5587be843a6c615ef4af179a29f24424ad75b95/dev_tools/docs/nxdl.py#L306) to 

```python
def _get_doc_line(self, ns, node):
  blocks = self._get_doc_blocks(ns, node)
  if len(blocks) == 0:
      return ""
  if len(blocks) > 1:
      return re.sub(r"\n", " ", "".join(blocks))
      # raise Exception(f"Unexpected multi-paragraph doc [{'|'.join(blocks)}]")
  return re.sub(r"\n", " ", blocks[0])
```

but this breaks the RST syntax inside the docstring:

![Bildschirmfoto 2024-01-03 um 14 53 58](https://github.com/FAIRmat-NFDI/nyaml/assets/1014422/b53497f5-41cf-4fac-b517-e724f1f617b4)

So the suggested solution is checking whether we are inside an enumeration docstring during nyaml2nxdl conversion and use the `3.35 <https://www.iso.org/obp/ui/en/#iso:std:iso:18115:-1:ed-3:v1:en:term:3.35>_` in-line syntax of RST in this case.

Edit: This idea is problematic as we cannot use `<` and `>` in nxdl because it is xml based.
